### ISSUE TITLE
Розібратись з середою розробки андроїд додатків

### ISSUE THREAD

**Issue by Petrenkoglw** [AndrewZolotoverkhyi/student_cstu_mobile#15]
- [x] Встановити середу розробки Android studio
- [x] Розібратися з найпростішими командами 
- [x] Зробити першу найпростішу програму на Android studio
